import Image from "next/image";
import Link from "next/link";

const projects = [
  {
    title: "AI Consistency Experiment",
    description:
      "An experimental study investigating whether consistency-focused instructions affect the consistency of responses generated by large language models.",
    image: "/project-images/ChatGPT_Image.png",
    href: "/projects/ai-consistency",
    tags: ["LLMs", "Experimentation", "NLP"],
  },

  {
    title: "FIFA 2026 World Cup Predictor",
    description:
      "A machine learning system designed to predict international soccer match outcomes and simulate the 2026 FIFA World Cup.",
    image: "/project-images/worldcupball.jpg",
    href: "/projects/world-cup",
    tags: ["Machine Learning", "Sports Analytics", "Python"],
  },

  {
    title: "eCommerce Graph Analytics",
    description:
      "A graph-based analysis of Amazon product relationships using PageRank, community detection, and node similarity.",
    image: "/project-images/ecommerce_graph_analytics.png",
    href: "/projects/ecommerce-graph",
    tags: ["Graph Analytics", "Python", "Recommendations"],
  },

  {
    title: "MLB Postseason Prediction",
    description:
      "A statistical analysis of Major League Baseball data investigating relationships between player and team performance.",
    image: "/project-images/mlb-postseason-prediction.jpg",
    href: "/projects/mlb-thesis",
    tags: ["Statistics", "MLB", "Data Analysis"],
  },

  {
    title: "NFL Officiating EDA",
    description:
      "An exploratory data analysis investigating patterns and trends in NFL officiating data.",
    image: "/project-images/nfl-officiating.jpg",
    href: "/projects/nfl-officiating",
    tags: ["EDA", "NFL", "Statistics"],
  },
];

export default function ProjectsPage() {
  return (
    <main className="min-h-screen bg-white py-24">

      <div className="max-w-6xl mx-auto px-6">

        {/* Back to Home */}
        <Link
          href="/"
          className="text-blue-600 hover:text-blue-700 transition"
        >
          ← Back to Home
        </Link>


        {/* Page Header */}
        <div className="mt-12">

          <div className="w-16 h-1 bg-blue-600 rounded-full mb-5" />

          <h1 className="text-5xl md:text-6xl font-bold text-gray-900">
            All Projects
          </h1>

          <p className="mt-6 text-xl text-gray-600 leading-8 max-w-3xl">
            A collection of my work across machine learning, statistics,
            data science, sports analytics, and artificial intelligence.
          </p>

        </div>


        {/* Projects Grid */}
        <section className="mt-16">

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">

            {projects.map((project) => (

              <Link
                key={project.title}
                href={project.href}
                className="group"
              >

                <article className="h-full border border-gray-200 rounded-xl overflow-hidden bg-white hover:shadow-lg transition duration-300">

                  {/* Project Image */}
                  <div className="relative aspect-video overflow-hidden bg-gray-100">

                    <Image
                      src={project.image}
                      alt={project.title}
                      fill
                      className="object-cover group-hover:scale-105 transition duration-300"
                    />

                  </div>


                  {/* Project Content */}
                  <div className="p-6">

                    <h2 className="text-2xl font-bold text-gray-900 group-hover:text-blue-600 transition">

                      {project.title}

                    </h2>


                    <p className="mt-3 text-gray-600 leading-7">

                      {project.description}

                    </p>


                    {/* Tags */}
                    <div className="mt-5 flex flex-wrap gap-2">

                      {project.tags.map((tag) => (

                        <span
                          key={tag}
                          className="px-3 py-1 bg-gray-100 rounded-full text-xs font-medium text-gray-600"
                        >
                          {tag}
                        </span>

                      ))}

                    </div>


                    {/* View Project */}
                    <div className="mt-6 text-blue-600 font-medium">

                      View Project →

                    </div>

                  </div>

                </article>

              </Link>

            ))}

          </div>

        </section>


        {/* Bottom Navigation */}
        <div className="mt-16 pb-10">

          <Link
            href="/"
            className="text-blue-600 hover:text-blue-700 font-medium"
          >
            ← Back to Portfolio
          </Link>

        </div>

      </div>

    </main>
  );
}